import { Assets, AssetsManifest } from 'pixi.js';

/** List of assets grouped in bundles, for dynamic loading */
let assetsManifest: AssetsManifest = { bundles: [] };

/** Store bundles already loaded */
const loadedBundles: string[] = [];

/** Check if a bundle exists in assetManifest  */
function checkBundleExists(bundle: string) {
    return !!assetsManifest.bundles.find((b) => b.name === bundle);
}

/** Load assets bundles that have nott been loaded yet */
export async function loadBundles(bundles: string | string[]) {
    if (typeof bundles === 'string') bundles = [bundles];

    // Check bundles requested if they exists
    for (const bundle of bundles) {
        if (!checkBundleExists(bundle)) {
            throw new Error(`[Assets] Invalid bundle: ${bundle}`);
        }
    }

    // Filter out bundles already loaded
    const loadList = bundles.filter((bundle) => !loadedBundles.includes(bundle));

    // Skip if there is no bundle left to be loaded
    if (!loadList.length) return;

    // Load bundles
    console.log('[Assets] Load:', loadList.join(', '));
    await Assets.loadBundle(loadList);

    // Append loaded bundles to the loaded list
    loadedBundles.push(...loadList);
}

/** Check if all bundles are loaded, return false if any of them is not loaded yet  */
export function areBundlesLoaded(bundles: string[]) {
    for (const name of bundles) {
        // Return false if a single bundle is not present in the loaded list
        if (!loadedBundles.includes(name)) {
            return false;
        }
    }

    // All provided bundles are loaded
    return true;
}

/** Load the assets json manifest generated by assetpack */
async function fetchAssetsManifest(url: string) {
    const response = await fetch(url);
    const manifest = await response.json();
    if (!manifest.bundles) {
        throw new Error('[Assets] Invalid assets manifest');
    }
    return manifest;
}

function removeAndReplaceLoader() {
    const loader = document.getElementById('loader');
    if (loader) {
        loader.style.display = 'none';
    }

    const assetLoader = document.getElementById('asset-loader');
    if (assetLoader) {
        assetLoader.style.display = 'block';
    }

    const canvas = document.querySelector('canvas');
    if (canvas) {
        canvas.style.display = 'none';
    }
}

/** Initialise and start background loading of all assets */
export async function initAssets() {
    // Load assets manifest
    assetsManifest = await fetchAssetsManifest('assets/assets-manifest.json');

    // Add fonts bundle
    Assets.addBundle('fonts', {
        'Spartan MB Bold': 'fonts/SpartanMB-Bold.otf',
        'Spartan MB Extra Bold': 'fonts/SpartanMB-Extra-Bold.otf',
    });

    // Init PixiJS assets with this asset manifest
    await Assets.init({ manifest: assetsManifest, basePath: 'assets' });

    // Load the fonts bundle BEFORE preload
    await Assets.loadBundle('fonts');

    // Load assets for the load screen
    // await loadBundles('preload');

    // Remove the loader once preload is complete
    removeAndReplaceLoader();

    // List all existing bundles names
    const allBundles = assetsManifest.bundles.map((item) => item.name);

    // Start up background loading of all bundles and track progress
    await loadAllBundlesWithProgress(allBundles);
}

/** Load all bundles with progress tracking */
async function loadAllBundlesWithProgress(bundles: string[]) {
    const totalBundles = bundles.length;
    let loadedBundles = 0;

    for (const bundle of bundles) {
        await Assets.loadBundle(bundle, (progress) => {
            const bundleProgress = progress / totalBundles;
            const overallProgress = loadedBundles / totalBundles + bundleProgress;
            updateBackgroundLoadProgress(overallProgress);
        });

        loadedBundles++;
        updateBackgroundLoadProgress(loadedBundles / totalBundles);
    }

    onAllAssetsLoaded();
}

/** Update progress for all background assets */
function updateBackgroundLoadProgress(progress: number) {
    const percentage = Math.round(progress * 100);
    const bgProgress = document.getElementById('bg-progress');
    if (bgProgress) {
        bgProgress.style.width = `${percentage}%`;
    }

    if (progress === 1) {
        onAllAssetsLoaded();
    }
}

/** Called when all assets are fully loaded */
function onAllAssetsLoaded() {
    const bgProgress = document.getElementById('bg-progress');
    if (bgProgress) {
        bgProgress.style.display = 'none';
    }

    const canvas = document.querySelector('canvas');
    if (canvas) {
        canvas.style.display = 'block';
    }

    const assetLoader = document.getElementById('asset-loader');
    if (assetLoader) {
        assetLoader.style.display = 'none';
    }
}
